In [4]:

import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score


train = pd.read_csv('C:/Users/Lab2_30/Downloads/titanic.csv')
print(train.shape)

(891, 12)

In [5]:
NAs = pd.concat([train.isnull().sum()], axis=1, keys=["Train"])
NAs[NAs.sum(axis=1) > 0]

          Train
Age         177
Cabin       687
Embarked      2

In [6]:
train.pop("Cabin")
train.pop("Name")
train.pop("Ticket")

0             A/5 21171
1              PC 17599
2      STON/O2. 3101282
3                113803
4                373450
             ...
886              211536
887              112053
888          W./C. 6607
889              111369
890              370376
Name: Ticket, Length: 891, dtype: object

In [7]:
train.shape

(891, 9)

In [8]:
train["Age"] = train["Age"].fillna(train["Age"].mean())

In [9]:
train["Embarked"] = train["Embarked"].fillna(train["Embarked"].mode()[0])

In [10]:
train["Pclass"] = train["Pclass"].apply(str)

In [11]:
for col in train.dtypes[train.dtypes=="object"].index:
    for_dummy=train.pop(col)
    train=pd.concat([train, pd.get_dummies(for_dummy, prefix=col)], axis=1)
train.head()

,PassengerId,Survived,Age,SibSp,Parch,Fare,Pclass_1,Pclass_2,Pclass_3,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,1,0,22.0,1,0,7.2500,False,False,True,False,True,False,False,True
1,2,1,38.0,1,0,71.2833,True,False,False,True,False,True,False,False
2,3,1,26.0,0,0,7.9250,False,False,True,True,False,False,False,True
3,4,1,35.0,1,0,53.1000,True,False,False,True,False,False,False,True
4,5,0,35.0,0,0,8.0500,False,False,True,False,True,False,False,True

In [12]:
labels = train.pop("Survived")

In [13]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(train, labels, test_size = 0.25)

In [14]:
from sklearn.tree import DecisionTreeClassifier

In [15]:
df_model=DecisionTreeClassifier(max_depth=14)

In [16]:
df_model.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=14)

In [17]:
train_y_hat=df_model.predict(x_train)
test_y_hat=df_model.predict(x_test)

In [18]:
y_pred=df_model.predict(x_test)

In [19]:
accuracy=accuracy_score(y_test,y_pred)

In [21]:
accuracy

0.7802690582959642

In [34]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier

boosting_model = AdaBoostClassifier(estimator=DecisionTreeClassifier(), n_estimators=50, random_state=42)

In [33]:
boosting_model.fit(x_train, y_train)

NameError: name 'boosting_model' is not defined

In [25]:
boosting_predictions = boosting_model.predict(x_test)

NameError: name 'boosting_model' is not defined

In [26]:
boosting_accuracy = accuracy_score(y_test, boosting_predictions)

NameError: name 'boosting_predictions' is not defined

In [23]:
print("Boosting Accuracy : ",boosting_accuracy)

NameError: name 'boosting_accuracy' is not defined

In [ ]:
# gradient boosting

In [38]:
from sklearn.metrics import classification_report

print("\n Classification Report: \n",classification_report(y_test, y_pred))

 Classification Report:
               precision    recall  f1-score   support

           0       0.85      0.80      0.83       146
           1       0.66      0.74      0.70        77

    accuracy                           0.78       223
   macro avg       0.76      0.77      0.76       223
weighted avg       0.79      0.78      0.78       223