In [1]:

import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score


train = pd.read_csv('C:/Users/Lab2_30/Downloads/titanic.csv')
print(train.shape)

(891, 12)

In [2]:
NAs = pd.concat([train.isnull().sum()], axis=1, keys=["Train"])
NAs[NAs.sum(axis=1) > 0]

          Train
Age         177
Cabin       687
Embarked      2

In [3]:
train.pop("Cabin")
train.pop("Name")
train.pop("Ticket")

0             A/5 21171
1              PC 17599
2      STON/O2. 3101282
3                113803
4                373450
             ...
886              211536
887              112053
888          W./C. 6607
889              111369
890              370376
Name: Ticket, Length: 891, dtype: object

In [4]:
train.shape

(891, 9)

In [5]:
train["Age"] = train["Age"].fillna(train["Age"].mean())

In [6]:
train["Embarked"] = train["Embarked"].fillna(train["Embarked"].mode()[0])

In [7]:
train["Pclass"] = train["Pclass"].apply(str)

In [8]:
for col in train.dtypes[train.dtypes=="object"].index:
    for_dummy=train.pop(col)
    train=pd.concat([train, pd.get_dummies(for_dummy, prefix=col)], axis=1)
train.head()

,PassengerId,Survived,Age,SibSp,Parch,Fare,Pclass_1,Pclass_2,Pclass_3,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,1,0,22.0,1,0,7.2500,False,False,True,False,True,False,False,True
1,2,1,38.0,1,0,71.2833,True,False,False,True,False,True,False,False
2,3,1,26.0,0,0,7.9250,False,False,True,True,False,False,False,True
3,4,1,35.0,1,0,53.1000,True,False,False,True,False,False,False,True
4,5,0,35.0,0,0,8.0500,False,False,True,False,True,False,False,True

In [9]:
labels = train.pop("Survived")

In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(train, labels, test_size = 0.25)

In [22]:
from sklearn.ensemble import GradientBoostingClassifier

In [23]:
gb_classifier = GradientBoostingClassifier(
    n_estimators = 100,
    learning_rate = 0.1,
    max_depth = 3,
    subsample = 0.8,
    random_state = 42
)

In [24]:
gb_classifier.fit(x_train,y_train)

GradientBoostingClassifier(random_state=42, subsample=0.8)

In [26]:
y_pred=gb_classifier.predict(x_test)

In [27]:
accuracy=accuracy_score(y_test,y_pred)
accuracy

0.8340807174887892

In [28]:
from sklearn.metrics import classification_report

print("\n Classification Report: \n",classification_report(y_test, y_pred))

 Classification Report:
               precision    recall  f1-score   support

           0       0.84      0.91      0.87       138
           1       0.82      0.72      0.77        85

    accuracy                           0.83       223
   macro avg       0.83      0.81      0.82       223
weighted avg       0.83      0.83      0.83       223